# Generated by Django 5.0.7 on 2025-06-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('fecha', models.DateField()),
                ('url', models.URLField()),
                ('destacado', models.BooleanField(default=False)),
            ],
        ),
    ]
